python3 main.py
Traceback (most recent call last):
  File "/home/mdlog/Downloads/NodeConnectBlockchain/main.py", line 1, in <module>
    from app import app, db
  File "/home/mdlog/Downloads/NodeConnectBlockchain/app.py", line 21, in <module>
    db.create_all()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5868, in create_all
    bind._run_ddl_visitor(
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3252, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3242, in begin
    with self.connect() as conn:
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
    return self._connection_cls(self)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 949, in connect
    await_only(creator_fn(*arg, **kw)),
  File "/home/mdlog/Downloads/NodeConnectBlockchain/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 123, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
